version: '2'


services:
  web-prod:
    build: .
    image: sandbox/go-app-bench
    # volumes:
      # - .:/go/src/app
    ports:
      - 8000:80
    depends_on:
      - redis

  redis:
    image: redis
